### ISSUE TITLE
Reputation change doesn't get recorded until I open the addon

### ISSUE THREAD

**Issue by joegnis** [LorenzoRogai/RepHub#1]
I have encountered this issue multiple times today so I think it is a legit case. 
So basically after I farm some rep with a toon A, log out without opening the addon right before, log into another toon B, open the addon, and it gives me outdated data. Then I relog into toon A, open the addon, relog into toon B, and then the up-to-date data show up.

Game version: 11.0.5.57534 Live
Addon version: 0.0.19

**Comment by LorenzoRogai** [comment]
Thanks for your report, i will check!

**Comment by LorenzoRogai** [comment]
@joegnis could you please check the version inside handle-update-faction-event branch? It should now handle UPDATE_FACTION event so if any reputation changes then the UI will have updated data (even without re-logging)

**Comment by LorenzoRogai** [comment]
@joegnis please check the latest release! It should now handle UPDATE_FACTION event so if a reputation changes then the UI will have updated data (even without re-logging)

**Comment by joegnis** [comment]
> @joegnis could you please check the version inside handle-update-faction-event branch? It should now handle UPDATE_FACTION event so if any reputation changes then the UI will have updated data (even without re-logging)

I tested that branch once with the same procedure as the description and it worked for that time
