### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by rubybrowncoat** [LorenzoRogai/RepHub#2]
Hey, this has definite potential. I have a couple of suggestions to fix my main gripes with it:

1. When clicking on a faction with a faction detail already open, replace the currently open detail with the new one to make flipping through factions a little bit easier. Also, clicking again on an open faction could just close the detail window.
2. ~~The faction detail overflows if there are more than 5 characters (with long realm names, like Pozzo). Solutions could be a scroll bar since we are mostly interested in the top results this shouldn't be much of an issue, or alternatively a dynamic detail height to accomodate all characters would work as well.~~ Solved in #4 
3. ESC should close the main window and the detail window.
4. There seems to be a conflict with addonskins (https://www.curseforge.com/wow/addons/addonskins), in particular when trying to resize the RepHub window resulting in a lua error.

Thanks for the addon, really helpful.

**Comment by LorenzoRogai** [comment]
Thanks for these suggestions. I'll review them soon

Regarding the last point, it's intentional since the addon currently doesn't support resizing. The library [Lib-ST](https://www.wowace.com/projects/lib-st) doesn't provide native functionality for table resizing.

**Comment by rubybrowncoat** [comment]
I see, I only brought the last point up because the UI has the "resize" graphic on the bottom right corner.

**Comment by Forcefulpuspus** [comment]
If I may piggyback on this suggestion post without creating an entirely new one: 

When you click on a rep (or mouseover?), give a brief description of the faction location zone and some descriptors (PvP, Firelands Raid, etc.). and if I may be so bold: Quartermaster location. 

Awesome addon with or without these changes. Thank you for your time. =)

**Comment by LorenzoRogai** [comment]
@rubybrowncoat all the other points should be fixed in the latest release! Could you please check?

@Forcefulpuspus i opened a new issue (#5) for tracking your suggestions better. Thanks!

**Comment by rubybrowncoat** [comment]
@LorenzoRogai everything seems to be working wonderfully. Thanks.
