### ISSUE TITLE
Factions in Sholazar Basin don't have WLK icon

### ISSUE THREAD

**Issue by joegnis** [LorenzoRogai/RepHub#6]
Specifically, the factions are the Oracles/Frenzyheart Tribe. 
Also, IMO, they should be grouped with other WLK factions and show up together when sorted by groups.

**Comment by LorenzoRogai** [comment]
It's fixed in 4e2f006dc4f3f38190c0a6c7ddf61092e080a493 but you need to launch "/rephub resetdb" command in order to update that column data

<img width="707" alt="image" src="https://github.com/user-attachments/assets/b22f5627-f62f-4135-8447-4068dcd6a16d">

**Comment by joegnis** [comment]
> It's fixed in [4e2f006](https://github.com/LorenzoRogai/RepHub/commit/4e2f006dc4f3f38190c0a6c7ddf61092e080a493) but you need to launch "/rephub resetdb" command in order to update that column data
> <img alt="image" width="707" src="https://private-user-images.githubusercontent.com/1665768/390431882-b22f5627-f62f-4135-8447-4068dcd6a16d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI3MzA0OTcsIm5iZiI6MTczMjczMDE5NywicGF0aCI6Ii8xNjY1NzY4LzM5MDQzMTg4Mi1iMjJmNTYyNy1mNjJmLTQxMzUtODQ0Ny00MDY4ZGNkNmExNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjdUMTc1NjM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmM5ODRhNzBkMWYwMjg5ZmI2ZDViZmQyMWVlMjZmMGJkNTExMmY1NDY3Mjk3ZmQ3MzRmY2RmZTlmNjQyYWJjOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.NNUlnysPndjNndxml7B2WP6Gl9rxlwdrox7GvcWM8ow">

Ah yes I had to reset db to let it show correctly
