### ISSUE TITLE
Mark Alliance/Horde-only factions

### ISSUE THREAD

**Issue by joegnis** [LorenzoRogai/RepHub#7]
like Alliance Vanguard/Horde Expedition in WLK

**Comment by LorenzoRogai** [comment]
@joegnis is this the same issue as this one? https://github.com/LorenzoRogai/RepHub/issues/6

If so, it has already been resolved as well

**Comment by joegnis** [comment]
> @joegnis is this the same issue as this one? #6
> 
> If so, it has already been resolved as well

I just resetdb and addon version is 0.3.4. There is no distinction between A/H-only factions from what I can tell, like Ironforge/Stormwind.
Sorry if I didn't state it clearly, I meant users should be able to tell easily if a faction is A/H-only on the UI. Maybe add an extra column with A/H/Neutral icon, add icon alongside A/H-only faction names, or something.

**Comment by LorenzoRogai** [comment]
Would something like this work?

<img width="272" alt="image" src="https://github.com/user-attachments/assets/bccd1853-e660-480c-b495-742c1c97b9dc">

**Comment by joegnis** [comment]
> Would something like this work?
> 
> <img width="272" alt="image" src="https://github.com/user-attachments/assets/bccd1853-e660-480c-b495-742c1c97b9dc">
> 

If you ask me, I'd prefer to add an A/H icon by the faction names in the table, either right after expansion icon or at the end. 
I think this would be more obvious than checking it in the pop-up window. 
Since there are not many A/H-only factions, this wouldn't cluster the UI too much. 
Just my 2 cents.

**Comment by LorenzoRogai** [comment]
I can prepend it to the left of the reputation name, similar to how expansion icons are displayed currently. However, I first need to complete the “detailed information” feature within the popup window. This will ensure I have the additional faction data needed to include that information in the main table as well

I'll let you know

**Comment by LorenzoRogai** [comment]
@joegnis please check now!
