### ISSUE TITLE
Reputation level filters

### ISSUE THREAD

**Issue by rubybrowncoat** [LorenzoRogai/RepHub#8]
I find myself wanting to filter out exalted reputations to see only what I need to work on. Given this I think a cool addition would be the ability to filter reputations by their level, maybe with a dropdown like the sources one on transmogs but with Exalted, Revered, etc, that way we can keep our focus on the reputations we want to see.
![image](https://github.com/user-attachments/assets/9f5d444a-1e2a-45df-a41a-7d9f2830fc94)

This should be a persistent configuration.

**Comment by LorenzoRogai** [comment]
I’ll look into adding a dropdown for this. In the meantime, you can achieve the same result by typing “Exalted” into the search bar, as the search applies to all columns

**Comment by LorenzoRogai** [comment]
@rubybrowncoat could you please check the "filter-dropdown" branch?

It should look like this

<img width="672" alt="image" src="https://github.com/user-attachments/assets/d8db2e31-45ec-4054-a700-e248d8569bcb">

**Comment by rubybrowncoat** [comment]
I tried the branch and it is working alright. It's a simple quick filter and definitely faster than writing the values yourself so that's a win. The ordering of the values could be better, since they are all over the place right now. 

It ultimately loses some of its true potential by not being a multi-selection facet filter like the Appearances / Toy Box ones I was mentioning, but it's a workable solution.

**Comment by LorenzoRogai** [comment]
@rubybrowncoat just pushed the feature. I will check soon on how to improve it even better. Thanks for the feedback!
